### ISSUE TITLE
Navbar Homepage link problem

### ISSUE THREAD

**Issue by Halim-Shams** [Halim-Shams/Medium-Clone#1]
I created a Navbar, but now I faced with a problem, there are 4 icon-links and defined active link design to it (when you click on a specific icon that icon color will change).
Every link has its own directory (link-path), if you are in Home page, the Home icon color changes, now if you click on other icons to go to that page still the Home page icon is active, instead I want that to return to the previous state.

Here is the screenshot:
![React App - Google Chrome 10_10_2022 4_20_52 PM](https://user-images.githubusercontent.com/96909515/194861626-a85eb7a2-cf71-499d-b440-d15fe7752ca5.png)

As you see I'm currently on Bookmarks link, but still the Home icon is active, whilst I want it to return to the previous state (no-color).

**Comment by riquelmebandeira** [comment]
Hey @Halim-Shams, i think i can help you with that. Can you assign this to me?
